"""initial schema

Revision ID: 07f7b6151968
Revises:
Create Date: 2026-09-20

The full domain model from BALOTLY_PROJECT_SPEC.md §4, as BE-01 asks for it:
organizations, users, contests, categories, candidates, vote_packages,
subaccounts, transactions, votes, settlements.

Written by hand rather than autogenerated so the parts that matter can be
said out loud:

``transactions.paystack_reference`` is unique. Paystack redelivers webhooks,
and a redelivery has to find the row it already credited and stop. That one
constraint is the idempotency key for the whole payment system.

``votes`` is an append-only ledger: one row per unit vote, no count column
anywhere, no ``updated_at``. A vote count is always ``COUNT(*)``, so it is
always reconstructable from confirmed transactions. A trigger refuses UPDATE
and DELETE on the table, because the ORM never needs either and a raw
statement that tries is a bug. Foreign keys out of ``votes`` and
``transactions`` are RESTRICT, not CASCADE: deleting a candidate must not
quietly erase the evidence of who paid what.

The one-vote-per-matric-number rule is a partial unique index on
``transactions``. It only applies when the contest asks for it, and an index
predicate cannot read another table, so the contest's flag is copied onto
each transaction at checkout as ``enforce_identity_cap``. Pending rows are
included so the duplicate is caught at insert time, before either voter has
been charged.

``organizations.created_by_user_id`` and ``users.organization_id`` point at
each other, so the first is added as a separate constraint once both tables
exist.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "07f7b6151968"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _timestamps() -> list[sa.Column]:
    return [
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    ]


def upgrade() -> None:
    op.create_table(
        "organizations",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("contact_email", sa.String(length=320), nullable=True),
        sa.Column("contact_phone", sa.String(length=20), nullable=True),
        sa.Column("platform_fee_percent", sa.Numeric(5, 2), nullable=True),
        sa.Column("created_by_user_id", postgresql.UUID(as_uuid=True), nullable=True),
        *_timestamps(),
        sa.CheckConstraint(
            "platform_fee_percent IS NULL "
            "OR (platform_fee_percent >= 0 AND platform_fee_percent <= 100)",
            name="ck_organizations_platform_fee_percent_range",
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "users",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("organization_id", postgresql.UUID(as_uuid=True), nullable=True),
        *_timestamps(),
        sa.CheckConstraint(
            "role IN ('admin', 'organizer', 'candidate')", name="ck_users_role"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_users_email", "users", ["email"], unique=True)
    op.create_index("ix_users_organization_id", "users", ["organization_id"])

    op.create_foreign_key(
        "fk_organizations_created_by_user_id_users",
        "organizations",
        "users",
        ["created_by_user_id"],
        ["id"],
        ondelete="SET NULL",
    )

    op.create_table(
        "contests",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("organization_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "status", sa.String(length=32), server_default="draft", nullable=False
        ),
        sa.Column(
            "requires_matric_number",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column(
            "caps_votes_per_identity",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column("platform_fee_percent", sa.Numeric(5, 2), nullable=True),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        *_timestamps(),
        sa.CheckConstraint(
            "status IN ('draft', 'active', 'closed')", name="ck_contests_status"
        ),
        sa.CheckConstraint("ends_at > starts_at", name="ck_contests_window"),
        sa.CheckConstraint(
            "platform_fee_percent IS NULL "
            "OR (platform_fee_percent >= 0 AND platform_fee_percent <= 100)",
            name="ck_contests_platform_fee_percent_range",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_contests_organization_id", "contests", ["organization_id"])
    op.create_index(
        "ix_contests_organization_status", "contests", ["organization_id", "status"]
    )

    op.create_table(
        "categories",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("contest_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        *_timestamps(),
        sa.ForeignKeyConstraint(["contest_id"], ["contests.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("contest_id", "name", name="uq_categories_contest_name"),
    )
    op.create_index("ix_categories_contest_id", "categories", ["contest_id"])

    op.create_table(
        "candidates",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("category_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("photo_url", sa.Text(), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("matric_number", sa.String(length=64), nullable=True),
        sa.Column("poster_url", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.String(length=32),
            server_default="pending_approval",
            nullable=False,
        ),
        sa.Column("disqualification_reason", sa.Text(), nullable=True),
        *_timestamps(),
        sa.CheckConstraint(
            "status IN ('pending_approval', 'approved', 'disqualified')",
            name="ck_candidates_status",
        ),
        sa.CheckConstraint(
            "status <> 'disqualified' OR disqualification_reason IS NOT NULL",
            name="ck_candidates_disqualified_has_reason",
        ),
        sa.ForeignKeyConstraint(
            ["category_id"], ["categories.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_candidates_category_id", "candidates", ["category_id"])
    op.create_index("ix_candidates_user_id", "candidates", ["user_id"])
    op.create_index("ix_candidates_slug", "candidates", ["slug"], unique=True)
    op.create_index(
        "ix_candidates_category_status", "candidates", ["category_id", "status"]
    )

    op.create_table(
        "vote_packages",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("contest_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("amount_kobo", sa.BigInteger(), nullable=False),
        sa.Column("vote_count", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=64), nullable=False),
        *_timestamps(),
        sa.CheckConstraint("amount_kobo > 0", name="ck_vote_packages_amount_positive"),
        sa.CheckConstraint("vote_count > 0", name="ck_vote_packages_votes_positive"),
        sa.ForeignKeyConstraint(["contest_id"], ["contests.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_vote_packages_contest_id", "vote_packages", ["contest_id"])

    op.create_table(
        "subaccounts",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("candidate_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("bank_code", sa.String(length=16), nullable=False),
        sa.Column("account_number_encrypted", sa.LargeBinary(), nullable=False),
        sa.Column("account_name", sa.String(length=255), nullable=True),
        sa.Column("subaccount_code", sa.String(length=64), nullable=True),
        sa.Column("percentage_charge", sa.Numeric(5, 2), nullable=True),
        sa.Column(
            "settlement_schedule",
            sa.String(length=16),
            server_default="manual",
            nullable=False,
        ),
        sa.Column(
            "status", sa.String(length=32), server_default="pending", nullable=False
        ),
        *_timestamps(),
        sa.CheckConstraint(
            "status IN ('pending', 'verified')", name="ck_subaccounts_status"
        ),
        sa.CheckConstraint(
            "status <> 'verified' OR subaccount_code IS NOT NULL",
            name="ck_subaccounts_verified_has_code",
        ),
        sa.CheckConstraint(
            "percentage_charge IS NULL "
            "OR (percentage_charge >= 0 AND percentage_charge <= 100)",
            name="ck_subaccounts_percentage_charge_range",
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"], ["candidates.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("candidate_id"),
        sa.UniqueConstraint("subaccount_code"),
    )

    op.create_table(
        "transactions",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("candidate_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("vote_package_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("contest_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("paystack_reference", sa.String(length=100), nullable=False),
        sa.Column("amount_kobo", sa.BigInteger(), nullable=False),
        sa.Column(
            "status", sa.String(length=32), server_default="pending", nullable=False
        ),
        sa.Column("voter_matric_number", sa.String(length=64), nullable=True),
        sa.Column("voter_phone", sa.String(length=20), nullable=True),
        sa.Column(
            "enforce_identity_cap",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        *_timestamps(),
        sa.CheckConstraint(
            "status IN ('pending', 'success', 'failed')",
            name="ck_transactions_status",
        ),
        sa.CheckConstraint("amount_kobo > 0", name="ck_transactions_amount_positive"),
        sa.CheckConstraint(
            "status <> 'success' OR confirmed_at IS NOT NULL",
            name="ck_transactions_success_is_confirmed",
        ),
        sa.CheckConstraint(
            "NOT enforce_identity_cap OR voter_matric_number IS NOT NULL",
            name="ck_transactions_cap_needs_matric_number",
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"], ["candidates.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["vote_package_id"], ["vote_packages.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["contest_id"], ["contests.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_transactions_candidate_id", "transactions", ["candidate_id"])
    op.create_index(
        "ix_transactions_vote_package_id", "transactions", ["vote_package_id"]
    )
    op.create_index("ix_transactions_contest_id", "transactions", ["contest_id"])
    op.create_index(
        "ix_transactions_paystack_reference",
        "transactions",
        ["paystack_reference"],
        unique=True,
    )
    op.create_index(
        "ix_transactions_candidate_status", "transactions", ["candidate_id", "status"]
    )
    op.create_index(
        "ix_transactions_contest_status", "transactions", ["contest_id", "status"]
    )
    op.create_index(
        "uq_transactions_identity_cap",
        "transactions",
        ["contest_id", "voter_matric_number"],
        unique=True,
        postgresql_where=sa.text(
            "enforce_identity_cap AND status IN ('pending', 'success')"
        ),
    )

    op.create_table(
        "votes",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("transaction_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("candidate_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"], ["transactions.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"], ["candidates.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_votes_transaction_id", "votes", ["transaction_id"])
    op.create_index("ix_votes_candidate_created", "votes", ["candidate_id", "created_at"])

    # The ledger is append-only. Refuse every statement that could make a
    # count disagree with the payment log. TRUNCATE gets its own trigger
    # because it does not fire row-level ones.
    op.execute(
        """
        CREATE FUNCTION votes_forbid_mutation() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'votes is an append-only ledger: % is not allowed',
                TG_OP USING ERRCODE = 'restrict_violation';
        END;
        $$;
        """
    )
    op.execute(
        """
        CREATE TRIGGER votes_append_only
        BEFORE UPDATE OR DELETE ON votes
        FOR EACH ROW EXECUTE FUNCTION votes_forbid_mutation();
        """
    )
    op.execute(
        """
        CREATE TRIGGER votes_no_truncate
        BEFORE TRUNCATE ON votes
        FOR EACH STATEMENT EXECUTE FUNCTION votes_forbid_mutation();
        """
    )

    op.create_table(
        "settlements",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("candidate_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("amount_kobo", sa.BigInteger(), nullable=False),
        sa.Column(
            "status", sa.String(length=32), server_default="held", nullable=False
        ),
        sa.Column("actioned_by_user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("actioned_at", sa.DateTime(timezone=True), nullable=True),
        *_timestamps(),
        sa.CheckConstraint(
            "status IN ('held', 'released', 'reversed')",
            name="ck_settlements_status",
        ),
        sa.CheckConstraint(
            "amount_kobo >= 0", name="ck_settlements_amount_non_negative"
        ),
        sa.CheckConstraint("period_end >= period_start", name="ck_settlements_period"),
        sa.CheckConstraint(
            "status = 'held' OR actioned_at IS NOT NULL",
            name="ck_settlements_action_is_timestamped",
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"], ["candidates.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["actioned_by_user_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_settlements_candidate_id", "settlements", ["candidate_id"])
    op.create_index(
        "ix_settlements_candidate_status", "settlements", ["candidate_id", "status"]
    )


def downgrade() -> None:
    op.drop_table("settlements")
    op.execute("DROP TRIGGER IF EXISTS votes_no_truncate ON votes")
    op.execute("DROP TRIGGER IF EXISTS votes_append_only ON votes")
    op.execute("DROP FUNCTION IF EXISTS votes_forbid_mutation()")
    op.drop_table("votes")
    op.drop_table("transactions")
    op.drop_table("subaccounts")
    op.drop_table("vote_packages")
    op.drop_table("candidates")
    op.drop_table("categories")
    op.drop_table("contests")
    op.drop_constraint(
        "fk_organizations_created_by_user_id_users", "organizations", type_="foreignkey"
    )
    op.drop_table("users")
    op.drop_table("organizations")
